export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_CHECK = 'LOGIN_CHECK';
export const AUTO_LOGIN_FAILED = 'AUTO_LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
