export const FETCH_FAVORITES_SEND = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_SET_DATA = 'FETCH_SET_DATA';
export const FETCH_FAVORITES_FAILED = 'FETCH_FAVORITES_FAILED';
// export const FETCH_FAVORITES_FETCHED = 'FETCH_FAVORITES_FETCHED';

export const DELETE_FAVORITE_SEND = 'DELETE_FAVORITE_SEND';
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const DELETE_FAVORITE_FAILED = 'DELETE_FAVORITES_FAILED';

export const ADD_FAVORITE_SEND = 'ADD_FAVORITE_SEND';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAILED = 'ADD_FAVORITE_FAILED';
export const ADD_FAVORITE_WARNING = 'ADD_FAVORITE_WARNING';

export const ADD_FAVORITE_LOCALLY = 'ADD_FAVORITE_LOCALLY';
export const DELETE_FAVORITE_LOCALLY = 'DELETE_FAVORITE_LOCALLY';
