export const ADD_FAVORITE_SEND = 'ADD_FAVORITE_SEND';
export const ADD_FAVORITE = 'ADD_FAVORITE';

export const DELETE_FAVORITE_SEND = 'DELETE_FAVORITE_SEND';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
