export const SET_FAVORITE_WEATHER_INFO = 'SET_FAVORITE_WEATHER_INFO';
export const SET_FAVORITE_WEATHER_INFO_DATA = 'SET_FAVORITE_WEATHER_INFO_DATA';
export const CHANGE_WEATHER_SCALE = 'CHANGE_WEATHER_SCALE';
export const CHANGE_DEFAULT_LOCATION = 'CHANGE_DEFAULT_LOCATION';
export const CHANGE_DEFAULT_VIEW = 'CHANGE_DEFAULT_VIEW';
