export const SET_FAVORITE_WEATHER_INFO = 'SET_FAVORITE_WEATHER_INFO';
export const SET_FAVORITE_WEATHER_INFO_SEND = 'SET_FAVORITE_WEATHER_INFO_SEND';
export const SET_FAVORITE_WEATHER_INFO_DATA = 'SET_FAVORITE_WEATHER_INFO_DATA';
export const SYNC_USER_SETTINGS = 'SYNC_USER_SETTINGS';
export const SYNC_USER_SETTINGS_SUCCESS = 'SYNC_USER_SETTINGS_SUCCESS';
export const SYNC_USER_SETTINGS_FAILED = 'SYNC_USER_SETTINGS_FAILED';
export const CHANGE_WEATHER_SCALE = 'CHANGE_WEATHER_SCALE';
export const CHANGE_DEFAULT_LOCATION = 'CHANGE_DEFAULT_LOCATION';
