export const WEATHER_MAP_API_SEND = 'WEATHER_MAP_API_SEND';
export const WEATHER_MAP_API_FAILED = 'WEATHER_MAP_API_FAILED';
export const WEATHER_MAP_SET_DATA = 'WEATHER_MAP_SET_DATA';
export const WEATHER_MAP_DELETE_BY_INDEX = 'WEATHER_MAP_DELETE_BY_INDEX';
